### PR TITLE
Goats/modal error handling

### LINKED ISSUE #841: [connect modal] Enhancement: better error handling
description: Currently, when connecting to a wallet fails we only show one message. We should show the user the error from the wallet/provider. Example: when user exits the wallet without connecting it fails. We should show: "User refused connection" or whatever the error says.

AC:
Display error message from wallet and fallback to default error if one does not exist.

### PR DESCRIPTION
**Pull request by goatsOnDrugs**
## Description
The modal now expects an errors object with "default" and "refused" keys. We can add more errors but the message from the provider will now be logged to the console correctly so people can send us helpful console logs if they have errors connecting

## Related Ticket

Resolves #841 

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

File: app/lib/constants.ts [hunk 1]
```diff
@@ -23,3 +24,14 @@ export const IS_STATIC_EXPORT = process.env.IS_STATIC_EXPORT;
...
   ? "https://checkout.offsetra.com/api/checkout"
   : "https://staging-checkout.offsetra.com/api/checkout";
+
+export const connectErrorStrings = {
+  default: t({
+    message: "We had some trouble connecting. Please try again.",
+    id: "connect_modal.error_message_default",
+  }),
+  rejected: t({
+    message: "User refused connection. Dont do that. Bad user.",
```
Comment (Atmosfearful) [inline app/lib/constants.ts:34]: lol lets be boring
```suggestion
    message: "User refused connection.",
```

File: site/lib/constants.ts [hunk 2]
```diff
@@ -12,3 +13,14 @@ export const MONTH_IN_SECONDS = 2592000;
...
   ? "http://localhost:3000"
   : urls.home;
+
+export const connectErrorStrings = {
+  default: t({
+    message: "We had some trouble connecting. Please try again.",
+    id: "connect_modal.error_message_default",
+  }),
+  rejected: t({
+    message: "User refused connection. Dont do that. Bad user.",
```
Comment (Atmosfearful) [inline site/lib/constants.ts:23]:
```suggestion
    message: "User refused connection.",
```

**Review by Atmosfearful — CHANGES_REQUESTED** [review]

File: app/lib/constants.ts (hunk 1 above)
Comment (goatsOnDrugs) [reply app/lib/constants.ts]: updated :)

**Review by Atmosfearful — APPROVED** [review]
