### PR TITLE
buttons to be explicitly circular via circle prop (861)

### LINKED ISSUE #861: regression: various buttons have a circle style applied
Various buttons which previously did not have a circle style applied are now styled as circles.

| What | Before | After |
| ----- | ----- | ----- |
| Resource bar search and filter option button | image|image|
| Pledge form |  image | image |

Link to previous build before regression introduced: 
- [Resource center](https://klimadao-site-git-goats-icon-bug-klimadao.vercel.app/resources)
- [Pledge](https://klimadao-site-git-goats-icon-bug-klimadao.vercel.app/pledge)

I've tracked the style regressions to this line that applies the circle styles:
https://github.com/KlimaDAO/klimadao/blob/038e1a4666a8ab9984b0089afa0653aa7584c4b7/lib/components/Buttons/ButtonBase.tsx#L33-L37

### PR DESCRIPTION
**Pull request by 0xemc**
## Description

* Reverts changes made to automatically create circular buttons when only an `icon` prop was provided. This must now be explicitly set via the `circle` prop
* Font size and color are also no longer automatically inherited and must be explicitly set. 

## Related Ticket

Resolves #861

## Changes

| Before  | After  |
|---------|--------|
|image|image|

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Review by 0xAeterno — COMMENTED** [review]
Looking good @0xemc. Thanks for jumping on this one.
I did a quick scan and it's looking a lot better. One thing I did note was that the color of the icons in light mode don't look quite right. I'm not confident in saying this was a regression introduced at some point or it was always the case.
Would you be able to have a poke around?  I'm pretty sure the color should be the same as the placeholder text.

image

**Review by 0xAeterno — CHANGES_REQUESTED** [review]
As per comment above :)

File: lib/components/Buttons/ButtonBase.tsx [hunk 1]
```diff
@@ -22,6 +22,7 @@ export type ButtonBaseProps = {
   disabled?: boolean;
   /** Apply rounded corners */
   rounded?: boolean;
+  circle?: boolean;
```
Comment (Atmosfearful) [inline lib/components/Buttons/ButtonBase.tsx:25]: I assume circle and rounded are never both true. So how about:
```suggestion
  shape?: "default" | "rounded" | "circle";
```

Where 'default' is the fallback if no prop is provided.
This will require you to update ~19 instances where the `rounded` prop is used.

File: lib/components/Buttons/styles.ts [hunk 2]
```diff
@@ -53,6 +51,7 @@ const buttonBase = css`
 export const buttonPrimary = css`
   ${buttonBase};
   background-color: var(--klima-green);
+  color: white; /* same in darkmode */
```
Comment (Atmosfearful) [inline lib/components/Buttons/styles.ts:54]: So a new contrib @0xMakka was gonna tackle #880 as a first-ticket. Perhaps it's as easy as updating this line ahaha. Anyways ill leave that to him!

**Review by Atmosfearful — CHANGES_REQUESTED** [review]

File: lib/components/Buttons/ButtonBase.tsx (hunk 1 above)
Comment (0xemc) [reply lib/components/Buttons/ButtonBase.tsx]: Nice, that update with this 👍

File: lib/components/Buttons/styles.ts (hunk 2 above)
Comment (0xemc) [reply lib/components/Buttons/styles.ts:50]: To be fair there is a bit of selector wars going on so I doubt if this would be enough. See how he goes though.

**Comment by 0xemc** [comment]
> Looking good @0xemc. Thanks for jumping on this one. I did a quick scan and it's looking a lot better. One thing I did note was that the color of the icons in light mode don't look quite right. I'm not confident in saying this was a regression introduced at some point or it was always the case. Would you be able to have a poke around? I'm pretty sure the color should be the same as the placeholder text.
> 
> image
> 
> Edit: Looked into it a bit more and confirmed my suspicions it's also a regression at some point. Here's a screenshot of it way back in the day. Link to ancient preview build: `https://klimadao-site-git-release-pledge-klimadao.vercel.app/pledge/<address>` (@Atmosfearful surprised these builds are still up, does it cost us anything to keep these deployments?) image

Ok should definitely be good to go now as I removed all automatic styling and made everything explicit and opt-in.  Unfortunately in a lot of places the background and font colors are being set explicitly for svgs, backgrounds and font colors so it was going to be a nightmare to find all of those and make them work with the automatic style 🤷

I had a quick look around and everything seemed ok. If you find anything else let me know. Cheers!

**Comment by 0xAeterno** [comment]
> Ok should definitely be good to go now as I removed all automatic styling and made everything explicit and opt-in. Unfortunately in a lot of places the background and font colors are being set explicitly for svgs, backgrounds and font colors so it was going to be a nightmare to find all of those and make them work with the automatic style 🤷
> 
> I had a quick look around and everything seemed ok. If you find anything else let me know. Cheers!

Appreciate you having a scan through the codebase for other instances where this might be an issue @0xemc!
What you've addressed is perfectly fine :) We can raise and address future instances as they come.
One of the challenges having contributors come and go at the beginning, so it feels like a broader style review is required at some point to get alignment on how we do things, now that there seems to be more stability.

**Review by Atmosfearful — APPROVED** [review]

**Review by 0xAeterno — APPROVED** [review]

**Comment by 0xemc** [comment]
@0xAeterno @Atmosfearful looks like this is ready to go, just need it merged by someone with the power ⚡
