### PR TITLE
fix:1300 Token Pool Prices to use 1e6 decimals always

### LINKED ISSUE #1300: [staging API] Prices not aligned for same projects on different endpoints
## Description

The "marketplace" view is rendered with the data from the "projects" endpoint.
Production: api.carbonmark.com/api/projects
Staging: staging-api.carbonmark.com/api/projects

Currently, the Staging API gives back different **best prices** for projects when rendering data from the "projects" endpoint. But the best price for a single project endpoint is correct again.

**On STAGING**
This results in way too high prices on the "marketplace" view on Staging at the moment.
Where the Single project view is correct again.

#### Example project "VCS-1718-2013"

"marketplace staging"
https://staging-api.carbonmark.com/api/projects
=> Project Price for VCS-1718-2013: "1818399000000000000"
=> Frontend: https://staging.carbonmark.com/projects

"single view staging"
https://staging-api.carbonmark.com/api/projects/VCS-1718-2013
=> Project Price: "1.818399"
=> Frontend: https://staging.carbonmark.com/projects/VCS-1718-2013

**Compare with Production:**
"marketplace production"
https://api.carbonmark.com/api/projects
=> Project Price for VCS-1718-2013: "1818399"
=> Frontend: https://www.carbonmark.com/projects

"single view production"
https://api.carbonmark.com/api/projects/VCS-1718-2013
=> Project Price: "1.818399"
=> Frontend: https://www.carbonmark.com/projects/VCS-1718-2013

## **SCREENSHOTs STAGING**

**WRONG:**
Bildschirmfoto 2023-07-10 um 17 22 06

**CORRECT:**
Bildschirmfoto 2023-07-10 um 17 22 57

### PR DESCRIPTION
**Pull request by 0xemc**
## Description

Removes the check for PRODUCTION in order to use 1e6 decimals in all cases.

## Related Ticket

Resolves #1300

### CODE REVIEW

File: carbonmark-api/src/utils/helpers/utils.ts [hunk 1]
```diff
@@ -220,20 +220,11 @@ const getPoolPrice = async (
 
 /** @todo refactor this */
 export async function calculatePoolPrices(fastify: FastifyInstance) {
-  let decimals: number;
-  if (process.env.VERCEL_ENV == "production") {
-    decimals = 1e6;
-  } else {
-    decimals = 1e18;
-  }
```
Comment (0xemc) [inline carbonmark-api/src/utils/helpers/utils.ts:228]: @Atmosfearful @Najada do you happen to remember why we had this decimals if case here?

Also in carbonmark:

https://github.com/KlimaDAO/klimadao/blob/ea2d095d469677ed2b48a8615372a90f31323d17/lib/utils/getTokenDecimals/index.ts#L6

Comment (Atmosfearful) [reply carbonmark-api/src/utils/helpers/utils.ts:228]: Yea we had configured staging & previews to use testnet (mumbai), and we didn't have a 6 decimal ERC20 token on mumbai, so we used an 18 decimal one that najada already had.

**Review by Atmosfearful — APPROVED** [review]
