### PR TITLE
fix focus trap for connect and enter key listeners

### LINKED ISSUE #830: [connect modal] add a focus trap
We have a hook for this, should be easy

### PR DESCRIPTION
**Pull request by goatsOnDrugs**
## Description
I added tab indexes to the modal content because the focus trap wasn't working. The tabbing is off on the error step and I cant figure out why the tab indexes are getting messed up. I also added a handler for enter button press when buttons are focused.

## Related Ticket

Resolves #830 

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

File: lib/components/ConnectModal/index.tsx [hunk 1]
```diff
@@ -100,28 +100,42 @@ export const ConnectModal = (props: ConnectModalProps) => {
       <div className={styles.modalBackground} onClick={handleClose} />
       <div className={styles.modalContainer}>
         <div className={styles.modalContent} ref={focusTrapRef}>
-          <span className="title">
-            <Text t="h4">{getTitle(step)}</Text>
-            <button onClick={handleClose}>
+          <div className="title">
+            <div>
+              <Text t="h4" tabIndex={1}>
+                {getTitle(step)}
```
Comment (Atmosfearful) [inline lib/components/ConnectModal/index.tsx:106]: title doesn't need focus

File: lib/components/ConnectModal/index.tsx [hunk 2]
```diff
@@ -134,13 +148,25 @@ export const ConnectModal = (props: ConnectModalProps) => {
...
+                    handleConnect({
+                      wallet: showCoinbaseWallet ? "injected" : "coinbase",
+                    })
+                  }
+                  tabIndex={5}
                 >
                   <CoinbaseWalletIcon />
                   <Text t="button">Coinbase</Text>
                 </span>
                 <span
```
Comment (Atmosfearful) [inline lib/components/ConnectModal/index.tsx:162]: this is why focusTrap doesn't work-- only anchor tags, buttons and inputs are focusable. The focustrap hook grabs all buttons and injects the listeners for us.

So you can rip out all the keydown and tabindex stuff and just make sure every focusable element is a button

**Review by Atmosfearful — CHANGES_REQUESTED** [review]

File: lib/components/ConnectModal/index.tsx (hunk 2 above)
Comment (goatsOnDrugs) [reply lib/components/ConnectModal/index.tsx:162]: Ok! Yea that makes much more sense than adding tab index. TY!

Comment (goatsOnDrugs) [reply lib/components/ConnectModal/index.tsx]: updated to use proper html tags and now using css to show/hide elements so that the focus trap works properly when in error step and bc less code. Fun fact: MM doesn't support tabbing.

File: lib/components/ConnectModal/index.tsx (hunk 1 above)
Comment (goatsOnDrugs) [reply lib/components/ConnectModal/index.tsx]: I was tired lol. Friday brain fry. Deep fry day.

File: lib/components/ConnectModal/index.tsx [hunk 3]
```diff
@@ -106,100 +107,99 @@ export const ConnectModal = (props: ConnectModalProps) => {
...
+                <button
+                  className={styles.walletButton}
+                  onClick={() => handleConnect({ wallet: "injected" })}
+                >
+                  <BraveIcon />
+                  <Text t="button">Brave</Text>
+                </button>
+              )}
+              {showBrowserWallet && (
                 <span
```
Comment (Atmosfearful) [inline lib/components/ConnectModal/index.tsx:141]: missed one

File: lib/components/ConnectModal/index.tsx [hunk 4]
```diff
@@ -55,6 +55,7 @@ export const ConnectModal = (props: ConnectModalProps) => {
 
   const showBrave = eth?.isBraveWallet;
   const showMetamask = eth?.isMetaMask;
+  const shouldUseCoinbaseSDK = eth?.isCoinbaseWallet;
```
Comment (Atmosfearful) [inline lib/components/ConnectModal/index.tsx:58]: naming is misleading, if isCoinbaseWallet is true it means its injected so we don't need the SDK.

Id go with this:
```suggestion
  const isInjectedCoinbase = eth?.isCoinbaseWallet;
```

File: lib/components/ConnectModal/index.tsx [hunk 5]
```diff
@@ -106,100 +107,99 @@ export const ConnectModal = (props: ConnectModalProps) => {
...
-              </span>
-              <div
-                className={styles.torusButtons}
-                onClick={() => handleConnect({ wallet: "torus" })}
+              )}
+              <button
+                className={styles.walletButton}
+                onClick={() =>
+                  handleConnect({
+                    wallet: shouldUseCoinbaseSDK ? "injected" : "coinbase",
```
Comment (Atmosfearful) [inline lib/components/ConnectModal/index.tsx:153]:
```suggestion
                    wallet: isInjectedCoinbase ? "injected" : "coinbase",
```

**Review by Atmosfearful — CHANGES_REQUESTED** [review]

File: lib/components/ConnectModal/index.tsx (hunk 5 above)
Comment (goatsOnDrugs) [reply lib/components/ConnectModal/index.tsx]: updated

File: lib/components/ConnectModal/index.tsx (hunk 4 above)
Comment (goatsOnDrugs) [reply lib/components/ConnectModal/index.tsx]: oh good point. updated.

File: lib/components/ConnectModal/index.tsx (hunk 3 above)
Comment (goatsOnDrugs) [reply lib/components/ConnectModal/index.tsx]: updated

**Review by Atmosfearful — APPROVED** [review]
