### PR TITLE
fix showing the handle instead of beneficary address

### LINKED ISSUE #2134: [receipt] Profile section not showing display name
See https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/4 for example

As per the designs, if the user has a carbonmark profile we used to show the profile image and display name
Screenshot 2024-01-16 at 2 21 11 PM

Seems to be broken and defaulting to 0x address
Screenshot 2024-01-16 at 2 22 15 PM

### PR DESCRIPTION
**Pull request by johntremorsi**
## Description

Profile section not showing display name
[#2134](https://github.com/KlimaDAO/klimadao/issues/2134)

## Related Ticket

Closes #2134

Was
image

Is now 

image

### CODE REVIEW

File: carbonmark/components/pages/Retirements/SingleRetirement/BeneficiaryDetails/index.tsx [hunk 1]
```diff
@@ -37,7 +37,8 @@ export const BeneficiaryDetails: FC<Props> = (props) => {
           <Trans id="retirement.single.beneficiary.title">Beneficiary:</Trans>
         </Text>
         <Text t="h4">
-          {props.beneficiary ||
+          {carbonmarkUser?.handle ||
+            props.beneficiary ||
```
Comment (0xemc) [inline carbonmark/components/pages/Retirements/SingleRetirement/BeneficiaryDetails/index.tsx:41]: I'm not sure I understand why this fixes the issue.. Can you explain?

**Comment by 0xtapi** [comment]
The fix works as required by the ticket. I discovered a new bug while testing this, but I'm gonna create a new ticket for that. This one is fine 👍.

**Review by jabby09 — APPROVED** [review]

File: carbonmark/components/pages/Retirements/SingleRetirement/BeneficiaryDetails/index.tsx (hunk 1 above)
Comment (0xemc) [reply carbonmark/components/pages/Retirements/SingleRetirement/BeneficiaryDetails/index.tsx:41]: AH I see I didn't realise this was rendering as well. Got it

**Review by 0xemc — APPROVED** [review]
