### PR TITLE
add cards and assets and fix slider bug

### LINKED ISSUE #596: KI Landing Page - Featured Cards Updates
The KI Landing Page launched with repeated featured offset cards (https://www.klimadao.finance/infinity)

The task of this ticket is to update the cards to match what is on the LoveLetter site.

Requirements:
- From polygon to scb, take card content off loveletter (https://www.loveletter.klimadao.finance/)
- Additional logo assets here (https://www.figma.com/file/yuHMB1kZ1ko56x67WLKuuF/assets-for-atmos?node-id=0%3A1#241326238)
- The click action should to the retirement page, this can be found by clicking on the card in Love Letter. As example here is the one for Polygon (https://www.loveletter.klimadao.finance/?pgid=l1awgjlr-9f064cec-8fa5-4225-aef3-fd26496d28b9)

### PR DESCRIPTION
**Pull request by goatsOnDrugs**
## Description

added the new card assets and grabbed the copy, dates, and tons retired from love letter site. slider updated to account for card padding and now slides all the way to the end. 

## Related Ticket

Resolves #596 

## Checklist

- [x] Building the site with `npm run build-site` works without errors
- [x] Building the app with `npm run build-app` works without errors
- [x] I formatted JS and TS files with running `npm run format-all`

### CODE REVIEW

File: site/components/pages/Infinity/Cards/styles.ts [hunk 1]
```diff
@@ -63,7 +63,8 @@ export const rereouselItem = css`
   display: flex;
   box-sizing: border-box;
   flex-shrink: 0;
-  margin: 0 1rem;
+  padding: 0 1rem;
+  /* margin: 0 1rem; */
```
Comment (ladytrekker) [inline site/components/pages/Infinity/Cards/styles.ts:67]: Remove unused css

File: site/components/pages/Infinity/Cards/Card.tsx [hunk 2]
```diff
@@ -16,38 +16,41 @@ type Card = {
...
+  width?: number;
+  height?: number;
 };
 
 type Props = {
   card: Card;
 };
 
-export const Card: FC<Props> = ({ card }) => {
+export const Card: FC<Props> = (props) => {
```
Comment (ladytrekker) [inline site/components/pages/Infinity/Cards/Card.tsx:27]: Why do you prefer to not destructure props?
Saw that in another PR of yours too.
Just curious.

File: site/components/pages/Infinity/Cards/cards.ts [hunk 3]
```diff
@@ -10,60 +18,103 @@ export const cards = [
...
+    link: "https://www.klimadao.finance/retirements/0xa83148b098038f366534253704ae4ff3cf931b94",
     description:
-      "We're proud to offset 10+ years of carbon emissions from Olympus to become Climate Positive. From the Ohmies, with Love.",
-    tonsRetired: 33333,
-    date: "14 MAY 2022",
+      "Offsetra is proud to pledge to offset 484 tonnes from our operational emissions, including employee travel. KlimaDAO has initiated a paradigm shift in the voluntary carbon market and we are excited to contribute to the on-chain market's innovations in the years to come.",
+    tonsRetired: 510,
+    date: "26 MAR 2022",
+    width: 120,
+    height: 30,
```
Comment (ladytrekker) [inline site/components/pages/Infinity/Cards/cards.ts:54]: I would rename this to: `logoWidth` and `logoHeight`

otherwise this reads as a value for the whole card

File: site/components/pages/Infinity/Cards/cards.ts [hunk 4]
```diff
@@ -10,60 +18,103 @@ export const cards = [
...
   {
     logo: polygonLogo,
     link: "https://www.klimadao.finance/retirements/0x087a7afb6975a2837453be685eb6272576c0bc06",
     description:
-      "We care deeply about our work, and in turn we care deeply about preserving it. This also applies more generally, and we wish to preserve the planet which has afforded us this freedom.",
-    tonsRetired: 65201,
-    date: "10 MAY 2022",
+      "Together with Polygon, the broader blockchain industry needs to form a united front to fund, support, and leverage technoilogy that helps heal the earth, rather than destroy it",
+    tonsRetired: 104794,
+    date: "21 JUN 2022",
```
Comment (ladytrekker) [inline site/components/pages/Infinity/Cards/cards.ts:29]: Why not add logoWidth and logoHeight to every card?

What is the reason that only five cards do have these?
Either add these values to every card or to none?
How do future developers know when to add this and when not?

File: site/components/pages/Infinity/Cards/CardsSlider.tsx [hunk 5]
```diff
@@ -45,19 +45,6 @@ const useWidth = (elementRef: RefObject<HTMLElement>) => {
...
-          window
-            .getComputedStyle(elementRef.current)
-            .getPropertyValue("padding-left")
-        ) -
-        parseInt(
-          window
-            .getComputedStyle(elementRef.current)
-            .getPropertyValue("padding-right")
-        );
-
```
Comment (ladytrekker) [inline site/components/pages/Infinity/Cards/CardsSlider.tsx:60]: So this was the slider bug?
For the future: I would do this in a separate commit. 
This makes it much easier for reviewers to understand what your thought processes were and which code belongs to what exactly. 🙇

**Review by ladytrekker — APPROVED** [review]
Thanks @goatsOnDrugs 

Finally the sliders are complete ⭐ 
Also thanks for fixing the slider.

See some suggestions below.

File: site/components/pages/Infinity/Cards/Card.tsx (hunk 2 above)
Comment (ladytrekker) [reply site/components/pages/Infinity/Cards/Card.tsx:27]: NVM, let's see what Atmos says [here](https://github.com/KlimaDAO/klimadao/pull/591#discussion_r947505002)

Comment (Atmosfearful) [reply site/components/pages/Infinity/Cards/Card.tsx:27]: @ladytrekker it's the law 👮‍♂️ 

https://github.com/KlimaDAO/klimadao/wiki#do-not-destructure-props

File: site/components/pages/Infinity/Cards/CardsSlider.tsx (hunk 5 above)
Comment (goatsOnDrugs) [reply site/components/pages/Infinity/Cards/CardsSlider.tsx:60]: Ok! that makes sense. Yea this was the slider bug. I will separate bugs and what not into their own PRs in the future.

File: site/components/pages/Infinity/Cards/cards.ts (hunk 4 above)
Comment (goatsOnDrugs) [reply site/components/pages/Infinity/Cards/cards.ts:29]: Some of the images are already the correct size and some are too big so you can manually set height and width if needed. I was having trouble wrangling the images without setting width and height manually on the Image component.

File: site/components/pages/Infinity/Cards/Card.tsx [hunk 6]
```diff
@@ -16,38 +16,57 @@ type Card = {
...
+              alt="logo"
+              width={props.card.width}
+              height={props.card.height}
+              className={styles.cardImage}
+            />
+          ) : (
+            <Image
+              layout="intrinsic"
+              src={props.card.logo}
+              alt="logo"
```
[the remark this answers is not in the document]
Comment (goatsOnDrugs) [reply site/components/pages/Infinity/Cards/Card.tsx:46]: Good point, I added an `alt` property on card for the name

File: site/components/pages/Infinity/Cards/cards.ts (hunk 3 above)
Comment (goatsOnDrugs) [reply site/components/pages/Infinity/Cards/cards.ts]: updated

File: site/components/pages/Infinity/Cards/styles.ts (hunk 1 above)
Comment (goatsOnDrugs) [reply site/components/pages/Infinity/Cards/styles.ts]: oops, removed

**Review by Atmosfearful — APPROVED** [review]
