### PR TITLE
carbon: fix navigation structure

### LINKED ISSUE #1739: [klima data] Left nav loses focus when on a Details page
Page: all detail pages

Issue:
- When I open a Details page, the left nav loses focus of the primary page
- For example

image

### PR DESCRIPTION
**Pull request by sprrwhwk**
## Description

This PR fixes the navigation bars not updating properly when visiting detail pages. It also fixes the back button links so that they work as deep links rather than triggering the browsers back button functionality.

## Related Ticket

Resolves #1739

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

File: carbon/app/[locale]/details/token-bridge-breakdown/[bridge]/page.tsx [hunk 1]
```diff
@@ -2,8 +2,12 @@ import { t } from "@lingui/macro";
 import TokenPoolBreakdownCard from "components/cards/tokenDetails/TokenPoolBreakdownCard";
 import DetailPage from "components/pages/DetailPage";
 import { TokenDetailPageProps } from "components/pages/props";
+import { PageLinks } from "lib/PageLinks";
 import { capitalize } from "lodash";
 
+/*
+FIXME: Is this used?!
+*/
 export default function TokenBridgeBreakdownPage({
```
Comment (sprrwhwk) [inline carbon/app/[locale]/details/token-bridge-breakdown/[bridge]/page.tsx:11]: @biwano this seems to be unused. WDYT?

**Comment by sprrwhwk** [comment]
@jabby09 @0xtapi if / when you test this, please make sure to check all detail links and the back buttons. Additionally please check if the navigation elements show the active page correctly or not.

**Review by jabby09 — APPROVED** [review]
