### PR TITLE
Carbon dashboard lower priority fixes

### LINKED ISSUE #1506: [carbon dashboard] Use @use instead of @import in scss files
It feels safer.

### LINKED ISSUE #1628: [carbon dashboard] On vs Off page retired tab issues
Credits by vintage start dates and Credits tokenized vs credits issued by origin cards should be modified to provide better information.

### PR DESCRIPTION
**Pull request by biwano**
## Description

Lower priority fixes for carbon dashboard

## Related Ticket

Resolves #1506
Resolves #1628

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

File: carbon/components/PageHeader/PageHeader.tsx [hunk 1]
```diff
@@ -39,7 +40,11 @@ export const PageHeader: FC<{
       <div className={layout.desktopOnly}>
         <div className={styles.buttons}>
           <ChangeLanguageButton className={styles.changeLanguageButton} />
-          <Button className={styles.exploreButton}>Explore Marketplace</Button>
+          <Link href="https://www.carbonmark.com/">
```
Comment (sprrwhwk) [inline carbon/components/PageHeader/PageHeader.tsx:43]: let's use the link from the constants here

File: carbon/components/Skeleton/index.tsx [hunk 2]
```diff
@@ -1,9 +1,18 @@
 import { t } from "@lingui/macro";
 import styles from "./styles.module.scss";
-export default function Skeleton(props: { className?: string; text?: string }) {
-  const text = props.text === "undefined" ? t`Fetching data...` : props.text;
+export default function Skeleton(props: {
+  className?: string;
+  text?: string;
+  height?: number;
+}) {
+  const text = props.text === undefined ? t`Fetching data...` : props.text;
```
Comment (sprrwhwk) [inline carbon/components/Skeleton/index.tsx:8]:
```suggestion
  const text = props.text === undefined ? t`Fetching data…` : props.text;
```

File: carbon/components/Skeleton/index.tsx [hunk 3]
```diff
@@ -1,9 +1,18 @@
...
+  const style = props.height
+    ? {
+        minHeight: props.height,
+      }
+    : {};
```
Comment (sprrwhwk) [inline carbon/components/Skeleton/index.tsx:13]: can we use a classname and proper css here instead?

File: carbon/components/cards/tokenDetails/TokenVolumeOverTimeCard/index.tsx [hunk 4]
```diff
@@ -29,16 +30,25 @@ export default function TokenVolumeOverTimeCard(
     />
   );
 }
-
 /** Async server component that renders a Recharts client component */
 async function TokenVolumeOverTimeChart(props: TokenDetailsProps) {
```
Comment (sprrwhwk) [inline carbon/components/cards/tokenDetails/TokenVolumeOverTimeCard/index.tsx:34]: In this chart we show a white background which is not in line with the designs where we show full bars:

Current:

grafik

Designs:

grafik

Comment (sprrwhwk) [reply carbon/components/cards/tokenDetails/TokenVolumeOverTimeCard/index.tsx:34]: Also notice the colors, they should be more contrasty (blue from the alternate palette)

File: carbon/lib/charts/helpers.ts [hunk 5]
```diff
@@ -25,6 +26,48 @@ export function transformToPercentages<CI>(
...
+  const newData: ChartData<CI> = [];
+  while (date.isSameOrBefore(now, granularity)) {
+    let newItem: CI | undefined = data.find((item) => {
+      const itemDate = moment(item[dateField] as string).startOf(granularity);
+      return itemDate.isSame(date, granularity);
+    });
+    if (newItem === undefined) {
+      newItem = Object.assign({ ...data[0] });
+      configuration.forEach((conf) => {
+        if (newItem !== undefined) (newItem[conf.id] as number) = 0;
```
Comment (sprrwhwk) [inline carbon/lib/charts/helpers.ts:47]:
```suggestion
        (newItem![conf.id] as number) = 0;
```

**Review by sprrwhwk — CHANGES_REQUESTED** [review]
Nice work, small things that could be improved though 👍

File: carbon/components/PageHeader/PageHeader.tsx (hunk 1 above)
Comment (biwano) [reply carbon/components/PageHeader/PageHeader.tsx]: done in 82bbaa89

File: carbon/components/Skeleton/index.tsx (hunk 2 above)
Comment (biwano) [reply carbon/components/Skeleton/index.tsx:8]: I should remember this one!

File: carbon/components/Skeleton/index.tsx (hunk 3 above)
Comment (biwano) [reply carbon/components/Skeleton/index.tsx]: Done in 821f1568

File: carbon/lib/charts/helpers.ts (hunk 5 above)
Comment (biwano) [reply carbon/lib/charts/helpers.ts:47]: Nice nice!

File: carbon/components/cards/tokenDetails/TokenVolumeOverTimeCard/index.tsx (hunk 4 above)
Comment (biwano) [reply carbon/components/cards/tokenDetails/TokenVolumeOverTimeCard/index.tsx:34]: Hi @jabby09 @theprofessora, I went a little bit freestyle on the token details charts because I saw that they were copy/paste of each other. I took inspiration from the renders on the site currently on production. Can you give your feedback? should I try to adhere to the figma designs?
image

**Comment by theprofessora** [comment]
@biwano this works for me. My only note is that when the chart legend has only 2 values, let's use these two colors:

Blue1: 03045E
Blue 5: CCE4FF

**Comment by biwano** [comment]
> @biwano this works for me. My only note is that when the chart legend has only 2 values, let's use these two colors:
> 
> Blue1: 03045E Blue 5: CCE4FF

Ok We where still using the palette from v4. @sprrwhwk I updated the palette hoping nothing breaks.

**Review by sprrwhwk — APPROVED** [review]
