### PR TITLE
WIP: Build `resources/contact` view

### LINKED ISSUE #79: Build `/resources/contact` view
For v1, this will just be some links to forms. The header etc. should follow masamune's designs (dm me or him for access) but we won't build the whole form-fill and auto-emailer until a later version.

Here is the content that the page should have for v1.
You can figure out how to best lay it out on the page :)

---

# CONTACT
Questions, concerns, ideas? Here are a few ways you can get in touch. We love meeting institutions and individuals alike.

## Questions & Support
Join our [community](https://klimadao.finance/resources/community) Discord server and ask in the #questions channel. We have thousands of friendly, knowledgeable community members ready and willing to help you out.

## Careers
We're hiring! Until we finish building out our careers page, you can submit a resume by joining our [contributor's Discord server](https://discord.gg/uWvjTuZ65v) and following the application instructions for whichever department(s) interest you.

## Partnerships
Until we finish building out our partnerships page, we are directing potential partnership and collaboration inquiries to [this contact form](https://docs.google.com/forms/d/10ETkwPZyiiEz7BQSCEAxtXRSgQ9uTCO9LtaRqOVhoXk/viewform?chromeless=1&edit_requested=true).

## Media
If you are a journalist or content creator, our marketing team would love to meet you.
[TODO:  NEED A LINK OR EMAIL FROM MARKETING TEAM]
 
## Bug Reports
To file a bug report, join our [community](https://klimadao.finance/resources/community) Discord server and ask your question in the #bug-reports channel. Someone in our community will be happy to investigate and find a solution for you.

### PR DESCRIPTION
**Pull request by kaxline**
## Description

This PR adds the `resources/contact` page as well as the side nav for all `resources/` pages as indicated in the current Figma design. 

## Related Ticket

Resolves #79

## To do

- [x] Build nav for mobile views

## Checklist

- [X] Building the site with `npm run build-site` works without errors
- [X] Building the app with `npm run build-app` works without errors
- [X] I formatted JS and TS files with running `npm run format-all`

### CODE REVIEW

File: site/components/pages/Resources/Container/styles.ts [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+  height: 140px;
+  box-shadow: 0px 4px 28px rgba(0, 0, 0, 0.06);
+`;
+
+export const listItem = css`
+  display: flex;
+  flex-direction: row;
+  align-items: center;
+  height: 44px;
+  padding: 12px;
```
Comment (Atmosfearful) [inline site/components/pages/Resources/Container/styles.ts:39]: we need to use `rem` everywhere so that the UI scales evenly as the user's font-size does.

I did a reset on the root `html` so that 1rem = 10px

File: site/components/pages/Resources/Contact/index.tsx [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+import { FC, HTMLAttributes } from "react";
+import { Container } from "../Container";
+
+export type Props = HTMLHtmlElement & {};
+
+type H2Props = HTMLAttributes<HTMLHeadingElement> & {};
+
+const H2: FC<H2Props> = (props) => {
+  return (
+    <h2 {...props} className={styles.page_h2}>
```
Comment (Atmosfearful) [inline site/components/pages/Resources/Contact/index.tsx:30]: The parent won't be able to override classnames like this.
I believe you can do:

`className={cx(styles.page_h2, props.className)}`

Comment (Atmosfearful) [reply site/components/pages/Resources/Contact/index.tsx:30]: actually why do we need this component at all? Can't we target child `h2`s from the parent classes?

File: lib/components/Text/Paragraph.tsx [hunk 3]
```diff
@@ -0,0 +1,12 @@
+import React, { FC, HTMLAttributes } from "react";
+import * as styles from "./styles";
+
+type Props = HTMLAttributes<HTMLParagraphElement>;
+
+export const Paragraph: FC<Props> = (props) => {
+  return (
+    <p className={styles.copy} {...props}>
```
Comment (Atmosfearful) [inline lib/components/Text/Paragraph.tsx:8]: probably better to merge classnames rather than completely override. See my other comment on the `<H2>`

File: lib/components/Navigation/NavItemDesktop.tsx [hunk 4]
```diff
@@ -1,13 +1,41 @@
 import React, { FC } from "react";
 import * as styles from "./styles";
 
+export declare type LinkProps = {
```
Comment (Atmosfearful) [inline lib/components/Navigation/NavItemDesktop.tsx:4]: I don't think we need `export` or `declare` since its only used in this file, do we?
```suggestion
type LinkProps = {
```

File: lib/components/Navigation/NavItemDesktop.tsx [hunk 5]
```diff
@@ -1,13 +1,41 @@
...
+
 interface Props extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
   name: string;
   url: string;
   active?: boolean;
+  link?: Link;
 }
 
 export const NavItemDesktop: FC<Props> = (props) => {
+  if (props.link) {
```
Comment (Atmosfearful) [inline lib/components/Navigation/NavItemDesktop.tsx:35]: I'm starting to think we should just add nextjs as a dependency to the `lib`...

File: lib/components/Navigation/NavItemDesktop.tsx [hunk 6]
```diff
@@ -1,13 +1,41 @@
...
+    return <props.link href={props.url}>{props.name}</props.link>;
```
Comment (Atmosfearful) [inline lib/components/Navigation/NavItemDesktop.tsx:36]: don't next links need to wrap an `a` tag?

File: lib/constants/index.ts [hunk 7]
```diff
@@ -56,7 +56,7 @@ export const addresses = {
 };
 
 export const urls = {
-  home: "https://www.klimadao.finance/",
+  home: "/",
```
Comment (Atmosfearful) [inline lib/constants/index.ts:59]: we need the hardcoded url otherwise when used in the dapp, this will just take you to the dapp root rather than the landing page.
if you want root just inline `"/"`

File: lib/constants/index.ts [hunk 8]
```diff
@@ -68,6 +68,9 @@ export const urls = {
   stake: "https://dapp.klimadao.finance/#/stake",
   wrap: "https://dapp.klimadao.finance/#/wrap",
   bond: "https://dapp.klimadao.finance/#/bonds",
+  resources: "/resources",
```
Comment (Atmosfearful) [inline lib/constants/index.ts:71]: lets reserve this object for hardcoded URLs, these relative paths won't work in `dapp`. we can inline for now and later consider a new url object in `site/lib/constants`

File: site/components/pages/Resources/Contact/index.tsx [hunk 9]
```diff
@@ -0,0 +1,156 @@
...
+          <H2>
+            <Trans>Partnerships</Trans>
+          </H2>
+          <Paragraph>
+            <Trans>
+              Until we finish building out our partnerships page, we are
+              directing potential partnership and collaboration inquiries to{" "}
+              <a
+                href={
+                  "https://docs.google.com/forms/d/10ETkwPZyiiEz7BQSCEAxtXRSgQ9uTCO9LtaRqOVhoXk/viewform?chromeless=1&edit_requested=true"
```
Comment (Atmosfearful) [inline site/components/pages/Resources/Contact/index.tsx:108]: lets put this in the URLs object

File: site/components/pages/Resources/Container/index.tsx [hunk 10]
```diff
@@ -0,0 +1,142 @@
...
+
+export const Container: FC<Props> = (props) => {
+  const getListItemClasses = (name: PageName) => {
+    if (name === props.activePage) {
+      return cx(styles.listItem, styles.listItemActive);
+    }
+    return styles.listItem;
+  };
+
+  const _listItem = (name: PageName, textEl: ReactNode) => {
```
Comment (Atmosfearful) [inline site/components/pages/Resources/Container/index.tsx:36]: Smart, but inline function-components are a pattern we should avoid because they cause a complete re-mount of children every time the parent re-renders. It's not a problem here, but could be a problem if someone refactors and adds a tooltip or a fancy dropdown or something.

I always prefer idiomatic HTML and CSS, even though it's more verbose:

```jsx
<Link href="/resources/contact">
  <a data-active={props.activePage === "contact"}>
    <Trans>Contact</Trans>
    <ArrowBack className="arrow" />
  </a>
</Link>
```


```css
a[data-active="true"] {
  /* active styles */
};
.arrow {
  display: none;
};
a[data-active="true"] .arrow {
  display: block;
};
```

File: site/components/pages/Resources/Container/index.tsx [hunk 11]
```diff
@@ -0,0 +1,142 @@
...
+      </li>
+    );
+  };
+
+  return (
+    <>
+      <PageHead
+        production={IS_PRODUCTION}
+        title={t`Contact KlimaDAO`}
+        mediaTitle={t`Contact KlimaDAO`}
```
Comment (Atmosfearful) [inline site/components/pages/Resources/Container/index.tsx:54]: these need to be different for each page

**Review by Atmosfearful — CHANGES_REQUESTED** [review]
Looks amazing, so cool to see this coming together!! Really appreciate you taking this on

Three things I noticed in the layout:

1. Contact page content should have a width constraint (same for all views). The nav will grow long as we add pages, it needs space on the left
image

2. nav should be `position: sticky`. Good luck, this can be annoying to implement sometimes lol

3. something funky going on with the desktop header link styles

File: site/components/pages/Resources/Contact/index.tsx (hunk 2 above)
Comment (kaxline) [reply site/components/pages/Resources/Contact/index.tsx:30]: Yeah, good point. I'll remove.

File: lib/constants/index.ts (hunk 8 above)
Comment (kaxline) [reply lib/constants/index.ts:71]: Good idea! Didn't really think that through.

File: site/components/pages/Resources/Container/index.tsx (hunk 10 above)
Comment (kaxline) [reply site/components/pages/Resources/Container/index.tsx:36]: Yeah, much better. I have an aversion to data props for some reason so my brain goes sideways when it should be straightforward.

File: site/components/pages/Resources/Container/index.tsx (hunk 11 above)
Comment (kaxline) [reply site/components/pages/Resources/Container/index.tsx:54]: 🤦‍♂️

**Comment by Atmosfearful** [comment]
@kaxline sorry for the delay on reviewing. It looks great to me. I just noticed the yarn.lock though, can you delete that? we only use NPM plz 🙏

**Review by Atmosfearful — APPROVED** [review]
